#!/bin/sh
mkdir -p $FSDOOMDIR

cp kill renice ps $FSDOOMDIR/

touch $FSDOOMDIR/.fsdoom-data $FSDOOMDIR/.fsdoom-mapping
truncate $FSDOOMDIR/.fsdoom-data --size 0
truncate $FSDOOMDIR/.fsdoom-mapping --size 0

USER=`whoami`

find $HOME -name ".*" -prune -o -type f -print | while read p; do
  FILE=`ls -i1 "$p" | awk '{for(i=2;i<=NF;i++) printf FS$i;} END {print NL}'`
  INODE=`ls -i1 "$p" | awk '{print $1}'`
  echo $USER $INODE `basename "$FILE" | sed 's/ /_/g'` 1 >> $FSDOOMDIR/.fsdoom-data
  echo $INODE $FILE >> $FSDOOMDIR/.fsdoom-mapping
done
