#!/bin/sh
set -e

rm `grep '^'"$1" $FSDOOMDIR/.fsdoom-mapping | awk '{for(i=2;i<=NF;i++){printf FS$i} } END {printf NL}'`
grep -v " $1 " $FSDOOMDIR/.fsdoom-data > $FSDOOMDIR/.fsdoom-data2
mv $FSDOOMDIR/.fsdoom-data2 $FSDOOMDIR/.fsdoom-data
